"""Add previous owner id to Player

Revision ID: 1225660a90fc
Revises: 4dce44b50311
Create Date: 2016-08-07 21:34:44.103585

"""

# revision identifiers, used by Alembic.
revision = '1225660a90fc'
down_revision = '4dce44b50311'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('previous_owner_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'previous_owner_id')
    ### end Alembic commands ###
