"""Added two_qb to owner model

Revision ID: 134ae1b61e1
Revises: 8acc7986a32
Create Date: 2017-09-02 15:22:45.732162

"""

# revision identifiers, used by Alembic.
revision = '134ae1b61e1'
down_revision = '8acc7986a32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('two_qbs', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'two_qbs')
    ### end Alembic commands ###
