"""Init

Revision ID: 2220cdad58f
Revises: 
Create Date: 2018-12-21 22:44:59.566809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2220cdad58f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=16), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('bools', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('mfl_team_id', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('twitter', sa.String(length=32), nullable=True),
    sa.Column('keeperSet', sa.Boolean(), nullable=True),
    sa.Column('madeBid', sa.Boolean(), nullable=True),
    sa.Column('image_name', sa.String(length=128), nullable=True),
    sa.Column('two_qbs', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_table('draftpicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draftRound', sa.Integer(), nullable=True),
    sa.Column('pickInRound', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=16), nullable=True),
    sa.Column('mfl_id', sa.String(length=16), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('nfl_id', sa.String(length=32), nullable=True),
    sa.Column('rotoworld_id', sa.String(length=32), nullable=True),
    sa.Column('stats_id', sa.String(length=32), nullable=True),
    sa.Column('espn_id', sa.String(length=32), nullable=True),
    sa.Column('kffl_id', sa.String(length=32), nullable=True),
    sa.Column('sportsdata_id', sa.String(length=32), nullable=True),
    sa.Column('cbs_id', sa.String(length=32), nullable=True),
    sa.Column('mfl_team', sa.Integer(), nullable=True),
    sa.Column('previous_owner_id', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('contractStatus', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('contractYear', sa.String(length=16), nullable=True),
    sa.Column('tag', sa.String(length=8), nullable=True),
    sa.Column('upForBid', sa.Boolean(), nullable=True),
    sa.Column('finishedBidding', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mfl_team'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('owner_bidding_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('winningBid', sa.Boolean(), nullable=True),
    sa.Column('winningAmount', sa.Integer(), nullable=True),
    sa.Column('draftPick', sa.Integer(), nullable=True),
    sa.Column('bounty', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['owner_bidding_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probowl_roster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('qb', sa.Integer(), nullable=True),
    sa.Column('rb1', sa.Integer(), nullable=True),
    sa.Column('rb2', sa.Integer(), nullable=True),
    sa.Column('wr1', sa.Integer(), nullable=True),
    sa.Column('wr2', sa.Integer(), nullable=True),
    sa.Column('wr3', sa.Integer(), nullable=True),
    sa.Column('te', sa.Integer(), nullable=True),
    sa.Column('pk', sa.Integer(), nullable=True),
    sa.Column('dst', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dst'], ['players.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.ForeignKeyConstraint(['pk'], ['players.id'], ),
    sa.ForeignKeyConstraint(['qb'], ['players.id'], ),
    sa.ForeignKeyConstraint(['rb1'], ['players.id'], ),
    sa.ForeignKeyConstraint(['rb2'], ['players.id'], ),
    sa.ForeignKeyConstraint(['te'], ['players.id'], ),
    sa.ForeignKeyConstraint(['wr1'], ['players.id'], ),
    sa.ForeignKeyConstraint(['wr2'], ['players.id'], ),
    sa.ForeignKeyConstraint(['wr3'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probowl_roster')
    op.drop_table('bids')
    op.drop_table('scores')
    op.drop_table('players')
    op.drop_table('draftpicks')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    op.drop_table('states')
    op.drop_table('division')
    ### end Alembic commands ###
