"""Forgot Flex position in PB Roster

Revision ID: 3d44ac14c31
Revises: 2220cdad58f
Create Date: 2018-12-21 23:00:21.743203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d44ac14c31'
down_revision = '2220cdad58f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('probowl_roster', sa.Column('flex', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'probowl_roster', 'players', ['flex'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'probowl_roster', type_='foreignkey')
    op.drop_column('probowl_roster', 'flex')
    ### end Alembic commands ###
