"""initial migration

Revision ID: 3d7b7f0945b
Revises: None
Create Date: 2016-06-17 18:13:54.898206

"""

# revision identifiers, used by Alembic.
revision = '3d7b7f0945b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('team_name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('mfl_team_id', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('twitter', sa.String(length=32), nullable=True),
    sa.Column('keeperSet', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('team', sa.String(length=16), nullable=True),
    sa.Column('mfl_id', sa.String(length=16), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('nfl_id', sa.String(length=32), nullable=True),
    sa.Column('rotoworld_id', sa.String(length=32), nullable=True),
    sa.Column('stats_id', sa.String(length=32), nullable=True),
    sa.Column('espn_id', sa.String(length=32), nullable=True),
    sa.Column('kffl_id', sa.String(length=32), nullable=True),
    sa.Column('sportsdata_id', sa.String(length=32), nullable=True),
    sa.Column('cbs_id', sa.String(length=32), nullable=True),
    sa.Column('mfl_team', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('contractStatus', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('contractYear', sa.String(length=16), nullable=True),
    sa.Column('tag', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['mfl_team'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    ### end Alembic commands ###
