"""Adding alternate collateral to Bid

Revision ID: 59bf399fc6f1
Revises: 134ae1b61e1
Create Date: 2018-06-25 21:38:59.436290

"""

# revision identifiers, used by Alembic.
revision = '59bf399fc6f1'
down_revision = '134ae1b61e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bids', sa.Column('bounty', sa.Boolean(), nullable=True))
    op.add_column('bids', sa.Column('draftPick', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bids', 'draftPick')
    op.drop_column('bids', 'bounty')
    ### end Alembic commands ###
