"""Add image_name to Owner

Revision ID: 8acc7986a32
Revises: 1225660a90fc
Create Date: 2017-06-25 15:04:46.954970

"""

# revision identifiers, used by Alembic.
revision = '8acc7986a32'
down_revision = '1225660a90fc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owners', sa.Column('image_name', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owners', 'image_name')
    ### end Alembic commands ###
